tofix.csv
Fixes #60. Fixes #61. Fixes #62. Fixes #65. Fixes #66.
+Reordered misplaced entries
=> Expanding the list

tofix.csv
Added entries for HTTraQt, Jitsi, Mundus, Pomidor to *totfix.csv*
=> Added entries for HTTraQt, Jitsi, Mundus, Pomidor

tofix.csv
Fix for Scribus. Hardcoded on Arch Linux.
Fix for Streamtuner2
=> Added fixes for Scribus and Streamtuner2

tofix.csv
=> Added Ardour 4

tofix.csv
=> fixes Backup Tool and Mint Drivers

tofix.csv
Removed a dot at the end of the python icon lines 
This will fix #107
=> Fix python icons #107

readme.md, tofix.csv
@Foggalong, take a look all looks good now.
=> New icons ready to go

fix.sh, tofix.csv
=> Fixes Gdebi issue and restore issue too

fix.sh
=> Fixes no directory exists check

fix.sh
Change fix.sh, and implement atribute '-p' in mkdir sentences.
solving the problem reported by @fii34 in commentary held in [issue 149] (https://github.com/Foggalong/hardcode-fixer/issues/149#issuecomment-135035451)
=> change fix.sh mkdir commands

fix.sh
=> fixes an issue with local/global hardcoded apps

tofix.csv
=> Add grive & layout editor

tofix.csv
=> Fix matlab & jabref

fix.sh
Well the issue was that Pushbullet was having a space bettween Icon=Name, i just add a regex pattern to ignore this space
tested it with pushbullet & my weather indicator, everything works fine
=> Fix pushbullet not being detected

tofix.csv
=> Risk of Rain (Steam)

tofix.csv
Added PlayOnLinux to the csv file.
Hopefully it's done properly.
=> Added PlayOnLinux

tofix.csv
Enpass updated their desktop file name and the icon location/name
=> Add Enpass

tofix.csv
The icon already exists in Numix
=> Add Double Action: Boogaloo

tofix.csv
As requested in [#1427](https://github.com/numixproject/numix-icon-theme-circle/issues/1427)
=> Add Teamspeak 3

tofix.csv
=> add MasterPDFeditor

tofix.csv
Genymotion binary installer now creates desktop file
=> Add genymotion

fix.sh
This will correctly backup existing icons so if the user changes the theme, the old icon will be used
The next PR will be the support of Hardcoded icons i hope :)
=> Correctly backup icons

tofix.csv
Android Studio and Clion should be added as hardcoded apps too
This will fix #229
=> Add Android studio and Clion

tofix.csv
=> Fixes Franz and Gitkraken

tofix.csv
=> Fixes Cisco AnyConnect and Slack

tofix.csv
A fix for hardcoded icons is coming soon!
=> Fixes #249 #245 #244

tofix.csv
=> Fixes #252 #253 #254 #255 

tofix.csv
Fixes #271 #268 #267 #265 #264 #262 #257
=> Fixes #271 #268 #267 #265 #264 #262 #257

tofix.csv
Archlinux User Repository version
=> Add Genymotion (AUR)

fix.sh, readme.md, tofix.csv
Adding old fixes to tofix.sh
Adding extra paths for layout, layouttexteditor, layout3d 
Fixing some texts on README
=> Some fixes 

tofix.csv
=> Add Jetbrains Gogland support

tofix.csv
I've used `gigolo` as an icon name
=> Add gigolo fixes #294

tofix.csv
Fixes #315 #316 #314 #311 #312
=> Add QMC2, Zoom, Teamspeak3, Jupyter, Tor Browser support

tofix.csv
=> Fix phpstorm and vpaint

tofix.csv
Add Discord as it is installed by some packages.
=> Add additional Discord path

fix.sh, tofix.csv
@slothds added a line for Netbeans v8.2, this PR just brings that across to here.
=> Netbeans 8.2

fix.sh, tofix.csv
Reverts the change that @slothds made on their branch.
=> Merge slothds
